* complex
  A Clojure library designed to make graphs of the complex plane
** Overview
   Descriptive text with latex equations rendered via mathjax.
   Canvas animated graphics.

   Make graphs of the complex plane
   with equations marked up with latex
   and code sytax highlighted in clojure, clojurescript
   writing to an html canvas
   using custom complex geometry library.

   With interactive repl development  
   using server in compojure ring hiccup.
   
   With a browser repl using piggieback.

   Starting with regions of the plane and
   the nth roots of unity.

** Usage
**** cljs
     #+BEGIN_SRC shell
     lein cljsbuild once
     or
     lein cljsbuild auto
     #+END_SRC

     Add to project.clj:

     #+BEGIN_SRC clojure
     :cljsbuild
     {:builds
     [{:source-paths ["src/complex"]
     :compiler {:output-to "resources/public/js/complex.js"
                :optimizations :whitespace
                :pretty-print true}}]}
     #+END_SRC

     Will compile to public/resources/js/complex.js.

**** lein repl
     M-x cider-jack-in to start a clojure repl from Emacs.

     user=>
     #+BEGIN_SRC clojure
     (go)
     (reset)

     (in-ns 'complex.complex)
     ((mult-by i) one)
     #+END_SRC

     http://localhost:3005/hello.html

**** browser repl 
     Using piggieback:
     https://github.com/cemerick/piggieback

     In project.clj add:
     #+BEGIN_SRC clojure
     :dependencies [ [com.cemerick/piggieback "0.1.0"] ... ]
     :repl-options {:nrepl-middleware [cemerick.piggieback/wrap-cljs-repl]}
     #+END_SRC
     
     user=>
     #+BEGIN_SRC clojure
     (require 'cljs.repl.browser)
     (cemerick.piggieback/cljs-repl :repl-env (cljs.repl.browser/repl-env :port 9000))
   
     (.log js/console "hello")
     #+END_SRC
** Dependencies
    - clojure
    - clojurescript
    - core.async
    - leiningen
    - nrepl
    - piggieback
    - environ
    - ring
    - compojure
    - hiccup
    - MathJax LaTeX
    - twitter bootstrap
    - MathJax
** License
   Copyright © 2013 Walter P Babic

   Distributed under the Eclipse Public License either version 1.0 or (at
   your option) any later version.
